/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'voteCount' : bigint,
  'candidateName' : string,
  'candidateId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Voter { 'status' : VoterStatus, 'voterId' : string }
export type VoterStatus = { 'voted' : null } |
  { 'notVoted' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVoter' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'castVote' : ActorMethod<[string, string], undefined>,
  'deleteVoter' : ActorMethod<[string], undefined>,
  'getAllVoters' : ActorMethod<[], Array<Voter>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoteResults' : ActorMethod<[], Array<Candidate>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginVoter' : ActorMethod<[string], Voter>,
  'resetVoterStatus' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];