/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VoterStatus = IDL.Variant({
  'voted' : IDL.Null,
  'notVoted' : IDL.Null,
});
export const Voter = IDL.Record({
  'status' : VoterStatus,
  'voterId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Candidate = IDL.Record({
  'voteCount' : IDL.Nat,
  'candidateName' : IDL.Text,
  'candidateId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVoter' : IDL.Func([IDL.Text], [], []),
  'adminLogin' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'castVote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteVoter' : IDL.Func([IDL.Text], [], []),
  'getAllVoters' : IDL.Func([], [IDL.Vec(Voter)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoteResults' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginVoter' : IDL.Func([IDL.Text], [Voter], ['query']),
  'resetVoterStatus' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VoterStatus = IDL.Variant({
    'voted' : IDL.Null,
    'notVoted' : IDL.Null,
  });
  const Voter = IDL.Record({ 'status' : VoterStatus, 'voterId' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Candidate = IDL.Record({
    'voteCount' : IDL.Nat,
    'candidateName' : IDL.Text,
    'candidateId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVoter' : IDL.Func([IDL.Text], [], []),
    'adminLogin' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'castVote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteVoter' : IDL.Func([IDL.Text], [], []),
    'getAllVoters' : IDL.Func([], [IDL.Vec(Voter)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoteResults' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginVoter' : IDL.Func([IDL.Text], [Voter], ['query']),
    'resetVoterStatus' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };